name = "nil-monitor-api"
main = "workers/index.js"
compatibility_date = "2024-01-01"

[[d1_databases]]
binding = "DB"
database_name = "nil-monitor-db"
database_id = "c205339b-2bde-4f06-ab64-bedef8db1f53"

[triggers]
crons = ["*/15 * * * *", "0 11,21 * * *"]
